---
base_locale: en
data:
  yaml:
    write:
      # do not wrap lines at 80 characters
      line_width: -1
locales: [en, es, ca]
search:
  paths:
    - "./app/cells"
    - "./app/views"
    - "./lib"
  relative_roots:
    - "app/cells"
  exclude:
    - "app/assets"
  strict: false